### ISSUE TITLE
Should we use `P3 has note` or `rdfs:comment`?

### ISSUE THREAD

**Issue by stephenhart8** [chin-rcip/collections-model#32]
Both `P3 has note` and `rdfs:comment` can be used to add a note to an instance.

**The question is simple: which one would be best to use?**

`P3 has note` would mean stay in CIDOC CRM, but `rdfs:comment` is more widely used.

**Comment by KarineLeonardBrouillet** [comment]
Or maybe should one be used over the other in specific situations?

**Comment by Habennin** [comment]
what is the use case?

**Comment by stephenhart8** [comment]
We have no use cases for this particular "note" field. I was just wondering is there is any semantic differences between the two of them.

**Comment by stephenhart8** [comment]
With the discussions we had during our meeting on the 20th of January, we've come to the conclusion that `P3_has_note` has to be used when the note itself is part of the data (for example a note written by a curator on a specific date, or specific event).
The `rdfs:comment` should be used for describing classes and properties in the ontology, as suggested by the rdfs documentation:

> A textual comment helps clarify the meaning of RDF classes and properties. Such in-line documentation complements the use of both formal techniques (Ontology and rule languages) and informal (prose documentation, examples, test cases). A variety of documentation forms can be combined to indicate the intended meaning of the classes and properties described in an RDF vocabulary. Since RDF vocabularies are expressed as RDF graphs, vocabularies defined in other namespaces may be used to provide richer documentation.

Therefore, I think we should only use `P3_has_note` in our model.

**Comment by illip** [comment]
+1 for P3_has_note

**Comment by stephenhart8** [comment]
If everyone agrees, I think we can close this issue.

**Comment by eecanning** [comment]
+1

**Comment by Habennin** [comment]
Ok, so I just want to clarify something here, at the risk of being pedantic.

Traditionally in CIDOC CRM practice as taught and indeed demonstrated in the model by its position in the numbering, p3_has_note was conceived in order to be able to cover additional textual data of significant complexity and non structured nature that it could not be modelled and yet was of import. p3_has_note functioned within the ontology much like the dreaded column in the excel or db table 'comment' or 'note'. 

In discussions with the Arches Resource Modelling Working Group, however, and LinkedArt, the observation arose that 'notes' are often quite valuable information and information that one day could be semantized, probably by some forms of machine learning/nlp etc. Therefore, understanding these comments within their context is important. At that point, p3_has_comment does not cut it because all it does is allow you to dump a text string beside a node. 

So consider this scenario.

We have the 'Battle of Vimy Ridge' as name of an event in some list of Canadian events. This list also has some commentary fields. One says,

"Canadians, and only Canadians, call it the Battle of Vimy Ridge . . . In everyone else's historical lexicons, it was a limited tactical victory in the First World War's horrendous Battle of Arras, which the British and their allies lost.

"It had a negligible effect on the war's outcome. The Canadians had equal casualties and more strategic successes in other battles, such as Amiens and Passchendaele. If French or British rather than Canadian troops had driven the German enemy off Vimy Ridge, history probably would have forgotten about it."

the other says,

"Historians attribute the success of the Canadian Corps to technical and tactical innovation, meticulous planning, powerful artillery support and extensive training, as well as the inability of the 6th Army to properly apply the new German defensive doctrine. The battle was the first occasion when the four divisions of the Canadian Expeditionary Force fought together and it was made a symbol of Canadian national achievement and sacrifice."

If we follow the p3_has_note method then we would get

<http://battleofvimyridge.ca> a E5_Event;
     rdfs:label "Battle of Vimy Ridge";
     crm_p3_has_note "string1 goes here";
     crm_p3_has_note "string2 goes here" .

Now we have definitely related those texts to the model, but should we be happy? I would argue, no. These texts provide valuable insight from two different points of view of the relative importance of this one thing that we recognize together as some sort of happening 'Vimy Ridge'. 

Therefore, I would argue for this case, but also for the case where a curator would write a comment about an object, or a conservator write out an observation etc. that we should mode this data as a linguistic object as per [issue 20](https://github.com/chin-rcip/chin-rcip/issues/20) 

I'm not sure if I could see a use case for using p3 has note by itself. Perhaps as a comment on the content of the node?

**Comment by Habennin** [comment]
Oh and the Vimy Ridge references were

https://www.theglobeandmail.com/news/national/michael-valpy-on-the-making-of-the-vimy-myth/article20395965/

and

https://en.wikipedia.org/wiki/Battle_of_Vimy_Ridge

just for completeness

**Comment by KarineLeonardBrouillet** [comment]
Notes on verbal meeting 2020-02-17: 

P3 has note is about particular information that could not be mapped correctly so will mostly use curatorial note w/ linguistic object. P3 has note will not be used much. Everyone is in accord. 
P. do we need to keep p3? It might be useful to note where the data is messy. Documenting negatively would be good.

**Comment by VladimirAlexiev** [comment]
I agree to prefer P3 over rdfs:comment.

However there are 2 more to consider:
- afaik, linked.art uses `rdf:value` for the main textual content of a node when the node has no main structured content. Eg a Linguistic node (or whatever was the crm class name) with classification AAT:dimension would have its content eg "3cm by 5cm" in rdf:value
- how about rdfs:label? It has been used before, eg for the display value of a TimeSpan or the preferred name of a Person (of course, the latter is also recorded as a separate Appellation node). I also prefer to use P3 in such cases, for uniformity

**Comment by illip** [comment]
@VladimirAlexiev Thanks for +1 about P3 :)

1) I'm not sure if they are still using it, if I remember correctly, they are now using the new property `P190_has_symbolic_content` (e.g. the biographical content: https://linked.art/model/actor/#biography)

2) I would prefer to make a clear distinction between the `rdfs:label` and `P1_is_identified_by`. `rdfs:label` should be use to provide a human-readable version of a resource's name which can be different from the `E41_Appellation` or `E73_Information_Object`. We should have a clear protocol to label our nodes. For `E21_Person` is probably a good idea to use the name of the person. For other nodes like E73_Information_Object or E52_Time-Span, it might be more complicated.

**Comment by stephenhart8** [comment]
+1 for what Philippe said.
In my opinion, `rdfs:label` should be used to identify a node (to make it understandable for a human, as URIs are often not easy to understand), not to state its value.
I'll take the example of the TimeSpan of the birth of Alfred Laliberté:
![Exemple Label](https://user-images.githubusercontent.com/49342191/77182112-a133e380-6aa2-11ea-8e2c-412ee3c86c6b.png)

**Comment by illip** [comment]
Decisions to document in the TM:

1. We will not use `rdfs:comment` except if we create some classes or properties and it would be useful to comment on them.
2. `P3_has_note` will be used only to document the mapping process. For instance, if the image URL is not valid we will use `P3_has_note` to keep track of this information.
3. The [Curatorial Note](https://chin-rcip.github.io/collections-model/target-model/current/descriptive-information#curatorial-note) pattern should always be used for the museum's general note in order to keep a better semantic. Regarding the semantic of the curatorial note, we think it might be useful to add a path to describe the topic of the note.

**Comment by illip** [comment]
CHIN has decided to open a new Issue (#63) to discuss the Curatorial Note Topic. This is why I close this issue.
